# Generated by Django 6.1.1 on 2026-09-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
