# Generated by Django 6.1.1 on 2026-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Duration',
            field=models.IntegerField(),
        ),
    ]
