# Generated by Django 6.1.1 on 2026-09-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='Completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='Title',
            new_name='title',
        ),
    ]
